#!/usr/bin/env python3

"""
rrfs_monitor.py — RRFSv2X ensemble output monitor

For each of the past hourly cycles:

1. Check mem001 through mem030.
2. Require exactly one mpasout* file from each member.
3. Report the file availability for each member.
4. If all ensemble members have exactly one file, call process_cycle()
   from monitor_functions.py.
5. Write monitoring status to data/monitor_status.txt.
6. Automatically commit and push updated files under data/ only.

Figures generated by monitor_functions.py are kept local under figure/
and are not committed or pushed.
"""

import argparse
import datetime as dt
import subprocess
from pathlib import Path

import yaml

from monitor_functions import process_cycle


# ----------------------------------------------------------------------
# Paths
# ----------------------------------------------------------------------

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_CONFIG_FILE = SCRIPT_DIR / "config.yml"


# ----------------------------------------------------------------------
# Configuration
# ----------------------------------------------------------------------

def load_config(config_file: Path) -> dict:
    """Load YAML configuration."""

    if not config_file.is_file():
        raise FileNotFoundError(
            f"Configuration file not found: {config_file}"
        )

    with config_file.open("r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    if not config:
        raise ValueError(
            f"Configuration file is empty: {config_file}"
        )

    return config


# ----------------------------------------------------------------------
# Time
# ----------------------------------------------------------------------

def utc_now() -> dt.datetime:
    """Return the current UTC time."""

    return dt.datetime.now(dt.timezone.utc)


# ----------------------------------------------------------------------
# RRFS paths
# ----------------------------------------------------------------------

def get_member_dir(
    cycle_time: dt.datetime,
    member: int,
    rrfs_com: Path,
) -> Path:
    """Return the RRFS ensemble forecast directory for one member."""

    pdy = cycle_time.strftime("%Y%m%d")
    cyc = cycle_time.strftime("%H")
    member_name = f"mem{member:03d}"

    return (
        rrfs_com
        / f"rrfs.{pdy}"
        / cyc
        / "fcst"
        / "enkf"
        / member_name
    )


# ----------------------------------------------------------------------
# Generate monitoring status
# ----------------------------------------------------------------------

def generate_status(
    now: dt.datetime,
    config: dict,
    output_dir: Path,
) -> str:
    """Check ensemble members and process complete cycles."""

    monitor_config = config["common"]["rrfs_monitor"]

    rrfs_com = Path(
        monitor_config["rrfs_com"]
    )

    lookback_hours = int(
        monitor_config.get(
            "lookback_cycles",
            12,
        )
    )

    num_members = int(
        monitor_config.get(
            "num_members",
            30,
        )
    )

    file_pattern = monitor_config.get(
        "forecast_file_pattern",
        "mpasout*",
    )

    lines = []

    lines.append("=" * 80)
    lines.append("RRFSv2X Ensemble Forecast Monitor")
    lines.append("=" * 80)

    lines.append(
        f"Current UTC time: "
        f"{now:%Y-%m-%d %H:%M:%S UTC}"
    )

    lines.append(
        f"Lookback cycles: {lookback_hours}"
    )

    lines.append(
        f"Ensemble members: {num_members}"
    )

    lines.append(
        "Expected files per member: 1"
    )

    lines.append(
        f"File pattern: {file_pattern}"
    )

    current_cycle = now.replace(
        minute=0,
        second=0,
        microsecond=0,
    )

    # ------------------------------------------------------------------
    # Loop through recent hourly cycles
    # ------------------------------------------------------------------

    for hour_offset in range(
        lookback_hours
    ):

        cycle_time = (
            current_cycle
            - dt.timedelta(
                hours=hour_offset
            )
        )

        cycle_string = (
            cycle_time.strftime(
                "%Y%m%d%H"
            )
        )

        lines.append("")
        lines.append("=" * 80)
        lines.append(
            f"Cycle: {cycle_string}"
        )
        lines.append("=" * 80)

        complete_members = []
        incomplete_members = []

        # --------------------------------------------------------------
        # Check all ensemble members
        # --------------------------------------------------------------

        for member in range(
            1,
            num_members + 1,
        ):

            member_name = (
                f"mem{member:03d}"
            )

            member_dir = get_member_dir(
                cycle_time,
                member,
                rrfs_com,
            )

            # ----------------------------------------------------------
            # Member directory missing
            # ----------------------------------------------------------

            if not member_dir.is_dir():

                incomplete_members.append(
                    member_name
                )

                lines.append(
                    f"{member_name}: "
                    f"MISSING "
                    f"(directory not found)"
                )

                continue

            # ----------------------------------------------------------
            # Find forecast file
            # ----------------------------------------------------------

            files = sorted(
                path
                for path in member_dir.glob(
                    file_pattern
                )
                if path.is_file()
            )

            file_count = len(files)

            # ----------------------------------------------------------
            # Exactly one file
            # ----------------------------------------------------------

            if file_count == 1:

                complete_members.append(
                    member_name
                )

                lines.append(
                    f"{member_name}: OK "
                    f"({files[0].name})"
                )

            # ----------------------------------------------------------
            # No files
            # ----------------------------------------------------------

            elif file_count == 0:

                incomplete_members.append(
                    member_name
                )

                lines.append(
                    f"{member_name}: "
                    f"MISSING "
                    f"(no {file_pattern} file)"
                )

            # ----------------------------------------------------------
            # More than one matching file
            # ----------------------------------------------------------

            else:

                incomplete_members.append(
                    member_name
                )

                lines.append(
                    f"{member_name}: CHECK "
                    f"({file_count} matching files; "
                    f"expected 1)"
                )

        # --------------------------------------------------------------
        # Cycle summary
        # --------------------------------------------------------------

        cycle_complete = (
            len(complete_members)
            == num_members
        )

        lines.append("")
        lines.append("Summary:")

        lines.append(
            f"  Complete members: "
            f"{len(complete_members)}/"
            f"{num_members}"
        )

        if cycle_complete:

            lines.append(
                "  Status: COMPLETE"
            )

        else:

            lines.append(
                "  Status: INCOMPLETE"
            )

            lines.append(
                "  Incomplete members: "
                + ", ".join(
                    incomplete_members
                )
            )

        # --------------------------------------------------------------
        # Process complete cycle
        # --------------------------------------------------------------

        if cycle_complete:

            lines.append("")
            lines.append(
                "Processing cycle:"
            )

            try:

                output_file = process_cycle(
                    cycle_time=cycle_time,
                    config=config,
                    output_dir=output_dir,
                )

                lines.append(
                    f"  SUCCESS: "
                    f"{output_file.name}"
                )

            except Exception as exc:

                lines.append(
                    f"  ERROR: {exc}"
                )

        else:

            lines.append("")

            lines.append(
                "Processing cycle: "
                "SKIPPED "
                f"({num_members} complete members required)"
            )

    lines.append("")
    lines.append("=" * 80)

    return (
        "\n".join(lines)
        + "\n"
    )


# ----------------------------------------------------------------------
# Git
# ----------------------------------------------------------------------

def run_git(
    args: list[str],
    repo_root: Path,
    capture_output: bool = True,
) -> subprocess.CompletedProcess:
    """Run a Git command from the repository root."""

    return subprocess.run(
        ["git", *args],
        cwd=repo_root,
        capture_output=capture_output,
        text=True,
    )


def git_commit_and_push(
    repo_root: Path,
) -> bool:
    """
    Commit and push generated monitoring data.

    Only files under data/ are staged.

    Files under figure/ remain local and are NOT pushed.
    """

    # --------------------------------------------------------------
    # Verify Git repository
    # --------------------------------------------------------------

    result = run_git(
        [
            "rev-parse",
            "--is-inside-work-tree",
        ],
        repo_root,
    )

    if result.returncode != 0:

        print(
            "ERROR: Script directory is not "
            "inside a Git repository."
        )

        return False

    # --------------------------------------------------------------
    # Stage data only
    # --------------------------------------------------------------

    result = run_git(
        [
            "add",
            "data/",
        ],
        repo_root,
    )

    if result.returncode != 0:

        print(
            "ERROR: git add failed"
        )

        print(
            result.stderr.strip()
        )

        return False

    # --------------------------------------------------------------
    # Check whether anything changed
    # --------------------------------------------------------------

    result = run_git(
        [
            "diff",
            "--cached",
            "--quiet",
        ],
        repo_root,
        capture_output=False,
    )

    if result.returncode == 0:

        print(
            "No Git changes to commit."
        )

        return True

    if result.returncode != 1:

        print(
            "ERROR: Unable to check "
            "staged Git changes."
        )

        return False

    # --------------------------------------------------------------
    # Commit
    # --------------------------------------------------------------

    now = utc_now()

    commit_message = (
        f"Update RRFS monitor data "
        f"{now:%Y-%m-%d %H:%M UTC}"
    )

    result = run_git(
        [
            "commit",
            "-m",
            commit_message,
        ],
        repo_root,
    )

    if result.returncode != 0:

        print(
            "ERROR: git commit failed"
        )

        print(
            result.stderr.strip()
        )

        return False

    if result.stdout:

        print(
            result.stdout.strip()
        )

    # --------------------------------------------------------------
    # Push
    # --------------------------------------------------------------

    result = run_git(
        [
            "push",
        ],
        repo_root,
    )

    if result.returncode != 0:

        print(
            "ERROR: git push failed"
        )

        print(
            result.stderr.strip()
        )

        return False

    if result.stdout:

        print(
            result.stdout.strip()
        )

    if result.stderr:

        print(
            result.stderr.strip()
        )

    print(
        "RRFS monitor data successfully "
        "pushed to GitHub."
    )

    return True


# ----------------------------------------------------------------------
# Arguments
# ----------------------------------------------------------------------

def parse_args():
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description=(
            "RRFSv2X ensemble output monitor"
        )
    )

    parser.add_argument(
        "config",
        nargs="?",
        default=str(
            DEFAULT_CONFIG_FILE
        ),
        help=(
            "Path to configuration YAML file"
        ),
    )

    return parser.parse_args()


# ----------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------

def main() -> int:
    """Main program."""

    args = parse_args()

    config_file = (
        Path(args.config).resolve()
    )

    # ------------------------------------------------------------------
    # Load config
    # ------------------------------------------------------------------

    try:

        config = load_config(
            config_file
        )

    except Exception as exc:

        print(
            f"ERROR loading config: {exc}"
        )

        return 1

    monitor_config = (
        config["common"]["rrfs_monitor"]
    )

    # ------------------------------------------------------------------
    # Output directory
    # ------------------------------------------------------------------

    output_dir = (
        SCRIPT_DIR
        / monitor_config.get(
            "output_dir",
            "data",
        )
    )

    status_file = (
        output_dir
        / monitor_config.get(
            "status_file",
            "monitor_status.txt",
        )
    )

    output_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ------------------------------------------------------------------
    # Run monitor
    # ------------------------------------------------------------------

    now = utc_now()

    try:

        status = generate_status(
            now=now,
            config=config,
            output_dir=output_dir,
        )

    except Exception as exc:

        print(
            f"ERROR generating "
            f"monitor status: {exc}"
        )

        return 1

    # ------------------------------------------------------------------
    # Print status
    # ------------------------------------------------------------------

    print(
        status,
        end="",
    )

    # ------------------------------------------------------------------
    # Write status file
    # ------------------------------------------------------------------

    status_file.write_text(
        status,
        encoding="utf-8",
    )

    print()

    print(
        f"Status written to: "
        f"{status_file}"
    )

    print()

    # ------------------------------------------------------------------
    # Commit/push data only
    # ------------------------------------------------------------------

    if not git_commit_and_push(
        SCRIPT_DIR
    ):

        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(
        main()
    )